version: '3.9'
services:
  pgsql:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgsql-data:
